{
    'name': 'Sale Subscription Extension',
    'version': '1.0',
    'summary': 'Extends Sale Subscription with additional features',
    'sequence': -100,
    'description': """Long description of module's purpose""",
    'category': 'Sales',
    'author': 'Mingalar Sky Co., Ltd.',
    'website': 'https://www.mingalarsky.com',
    'license': 'LGPL-3',
    'depends': ['sale_subscription'],
    'data': [
        'security/ir.model.access.csv',
        'views/sale_subscription_adjustment_view.xml',
        'wizards/sale_subscription_adjustment_view.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}